'use client';
import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Check, ShieldCheck, CalendarDays, SlidersHorizontal, Monitor, Smartphone, Leaf, Play, Sparkles } from 'lucide-react';
import { HeroMobileAdSimulator } from '../components/HeroMobileAdSimulator';

export default function LandingPage() {
  const [device, setDevice] = useState<'desktop' | 'mobile'>('desktop');
  const [showDemo, setShowDemo] = useState(false);
  return <div className="landing">
    <header className="landing-nav"><Link className="landing-brand" href="/" aria-label="SubFlow accueil"><span className="brand-mark">∿</span>SubFlow<span className="brand-dot">.</span></Link><nav aria-label="Présentation"><a href="#comment">L’essentiel</a><a href="#confidentialite">Vie privée</a><Link className="nav-open" href="/app">Ouvrir l’app <ArrowUpRight size={15}/></Link></nav></header>
    <section className="landing-hero">
      <div className="hero-copy"><div className="eyebrow"><span/> MOINS DE SURPRISES. PLUS DE CLARTÉ.</div><h1>Vos prélèvements.<br/>Votre <em>tranquillité.</em></h1><p className="hero-description">Le streaming, le téléphone, la salle de sport…<br className="desktop-break"/> Retrouvez ce qui revient chaque mois. Voyez ce qui arrive. Décidez de ce qui reste.</p><div className="hero-actions"><Link className="primary-link" href="/app">Commencer gratuitement <ArrowRight size={18}/></Link><a className="text-link" href="#demo" onClick={() => setShowDemo(true)}>Explorer la démo <ArrowUpRight size={16}/></a></div><p className="hero-reassurance"><Check size={14}/>Sans compte obligatoire <span>·</span> Sans publicité</p><div className="hero-note"><span className="note-line"/>Un peu d’ordre dans les dépenses.<br/>Un peu d’espace dans la tête.</div></div>
      <div className="hero-visual">
        <div className="visual-label"><span className="live-dot"/> DÉMONSTRATION EN DIRECT<span>01 — APERÇU MOBILE</span></div>
        <HeroMobileAdSimulator />
        <p className="visual-caption">Vraie interface SubFlow · Scénario publicitaire interactif · Données fictives</p>
      </div>
    </section>
    <div className="value-strip"><span>Votre quotidien, en plus simple.</span><span><Check size={16}/>Abonnements & prélèvements</span><span><Check size={16}/>Calendrier des échéances</span><span><Check size={16}/>Simulation d’économies</span></div>
    <section id="comment" className="landing-section"><div className="section-heading"><div><span className="eyebrow">JUSTE CE QU’IL FAUT</span><h2>Comprendre. Anticiper.<br/><em>Choisir.</em></h2></div><p>Pas besoin de refaire toute votre comptabilité.<br/>SubFlow se concentre sur les dépenses qui reviennent.</p></div><div className="steps"><article><span className="step-number">01</span><h3>Tout retrouver.</h3><p>Ajoutez vos services, leur montant et leur fréquence. Les prélèvements mensuels et annuels trouvent leur place.</p><div className="step-footer"><span>À votre rythme</span><ArrowUpRight size={20}/></div></article><article><span className="step-number">02</span><h3>Voir ce qui arrive.</h3><p>Un coût mensuel équivalent pour prendre du recul. Un calendrier pour connaître les montants et les dates des prochaines échéances.</p><div className="step-footer"><span>Sans calcul mental</span><CalendarDays size={20}/></div></article><article><span className="step-number">03</span><h3>Faire de la place.</h3><p>Écartez un abonnement dans la simulation et voyez l’économie possible. Vous explorez une idée ; aucun service n’est résilié.</p><div className="step-footer"><span>Vous gardez la main</span><SlidersHorizontal size={20}/></div></article></div></section>
    <section id="demo" className="demo-section"><div className="demo-heading"><div><span className="eyebrow">ESSAYEZ, TOUT SIMPLEMENT</span><h2>La vraie app.<br/><em>À vous de jouer.</em></h2></div><div><p>Un scénario fictif, les vraies fonctionnalités.<br/>Ajoutez un service, explorez le calendrier ou simulez une économie.</p><div className="device-switch" role="group" aria-label="Format de la démonstration"><button aria-pressed={device === 'desktop'} onClick={() => setDevice('desktop')}><Monitor size={16}/>Ordinateur</button><button aria-pressed={device === 'mobile'} onClick={() => setDevice('mobile')}><Smartphone size={16}/>Mobile</button></div></div></div><div className={`demo-frame ${device}`}>
      {showDemo ? <iframe src="/demo" title="Démonstration interactive de SubFlow avec données fictives" sandbox="allow-scripts allow-same-origin"/> : <button className="demo-start" onClick={() => setShowDemo(true)}><span className="demo-play"><ArrowRight size={26}/></span><strong>Essayer SubFlow</strong><span>Une démo isolée de vos données personnelles</span></button>}
    </div><p className="demo-caption">La démo ne conserve pas vos changements. Les tarifs illustrent le scénario et ne constituent pas les offres actuelles des marques.</p></section>
    <section id="confidentialite" className="privacy-section"><div className="privacy-symbol"><ShieldCheck strokeWidth={1} size={100}/></div><div><span className="eyebrow">LA CONFIANCE SE MÉRITE</span><h2>Vos données.<br/><em>Vos choix.</em></h2><p>Commencez dans votre navigateur, sans connecter votre banque. Exportez vos données gratuitement, y compris dans un fichier chiffré avec votre mot de passe.</p><p className="privacy-detail">Le stockage du navigateur n’est pas chiffré par SubFlow. Une sauvegarde Google Drive est facultative et n’est pas chiffrée de bout en bout. Nous vous expliquons ces différences clairement.</p><Link className="text-link" href="/privacy">Lire notre politique de confidentialité <ArrowUpRight size={16}/></Link></div></section>
    <section className="closing-section"><span className="eyebrow">PLUS SIMPLE, DÈS AUJOURD’HUI</span><h2>Faites le point.<br/><em>Gardez l’esprit libre.</em></h2><p>Le suivi, la simulation et l’export sont gratuits.<br/>Pas de carte bancaire pour commencer.</p><Link className="primary-link" href="/app">Ajouter mon premier prélèvement <ArrowRight size={18}/></Link><a className="feedback-link" href="mailto:contact.aadatech@gmail.com?subject=Retour%20sur%20SubFlow">Une idée pour améliorer SubFlow ? Partagez-la.</a></section>
  </div>;
}
